# Entry point for home program modules
{
  imports = [
    ./alacritty.nix
    ./chrome.nix
    ./chromium.nix
    ./claude-code.nix
    ./common.nix
    ./dev-languages.nix
    ./dev-tools.nix
    ./direnv.nix
    ./firefox.nix
    ./librewolf.nix
    ./gaming.nix
    ./ghostty
    ./herdr.nix
    ./mise.nix
    ./git.nix
    ./nvim
    ./pi.nix
    ./reasonix.nix
    ./rofi.nix
    ./shell
    ./spotify.nix
    ./ssh.nix
    ./vscode.nix
    ./wezterm
    ./zotero.nix
    ./xdg.nix
    ./zellij.nix
  ];
}
