services:
  ddclient:
    container_name: ddclient
    environment:
      - PGID=0
      - PUID=0
      - TZ=America/Los_Angeles
    image: lscr.io/linuxserver/ddclient:latest
    labels:
      icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/ddclient-logo.png
      com.centurylinklabs.watchtower.enable: "true"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pgrep ddclient || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - type: bind
        source: ${CONFIG_PATH}
        target: /config
      - type: bind
        source: ${CONFIG_PATH}
        target: /etc/ddclient
    networks:
      - default
    privileged: false
