services:
  obsidian-couchdb:
    image: couchdb:3.5
    container_name: obsidian-couchdb
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - ${DATA_PATH}/couchdb/data:/opt/couchdb/data
      - ${DATA_PATH}/couchdb/etc:/opt/couchdb/etc/local.d
    environment:
      - TZ=${TZ}
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.obsidian-couchdb.entrypoints=http"
      - "traefik.http.routers.obsidian-couchdb.rule=Host(`obsidian-db.local.solivan.dev`) || Host(`obsidian-db.solivan.dev`)"
      - "traefik.http.middlewares.obsidian-couchdb-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.obsidian-couchdb.middlewares=obsidian-couchdb-https-redirect"
      - "traefik.http.routers.obsidian-couchdb-secure.entrypoints=https"
      - "traefik.http.routers.obsidian-couchdb-secure.rule=Host(`obsidian-db.local.solivan.dev`) || Host(`obsidian-db.solivan.dev`)"
      - "traefik.http.routers.obsidian-couchdb-secure.tls=true"
      - "traefik.http.routers.obsidian-couchdb-secure.middlewares=crowdsec-bouncer@docker"
      - "traefik.http.routers.obsidian-couchdb-secure.service=obsidian-couchdb"
      - "traefik.http.services.obsidian-couchdb.loadbalancer.server.port=5984"
      - "traefik.docker.network=proxy"
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  proxy:
    external: true
