# Tokyo Night color palette
palette = "tokyo-night"

format = """
[░▒▓](blue)\
[ $os ](bg:blue fg:bg-dark)\
$username\
$hostname\
$directory\
[ ](fg:blue bg:bg-medium)\
$git_branch\
$git_status\
[ ](fg:bg-medium bg:bg-dark)\
$nix_shell\
[ ](fg:bg-dark bg:bg-darker)\
$time\
[  ](fg:bg-darker)\
\n$character"""

[palettes.tokyo-night]
# Background colors
bg-darker = "#16161e"
bg-dark = "#1a1b26"
bg-medium = "#292e42"

# Accent colors
blue = "#7aa2f7"
red = "#f7768e"
green = "#5fd700"
yellow = "#d7af00"
red-bright = "#d70000"
fg-light = "#a9b1d6"

[directory]
style = "fg:bg-dark bg:blue bold"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
fish_style_pwd_dir_length = 1

# Username - only show on SSH
[username]
show_always = false
style_user = "fg:bg-dark bg:blue bold"
style_root = "fg:red bg:blue bold"
format = "[ $user]($style)"

# Hostname - only show on SSH
[hostname]
ssh_only = true
style = "fg:bg-dark bg:blue bold"
format = "[@$hostname ]($style)"

[os]
disabled = false
style = "fg:bg-dark bg:blue"
format = '[$symbol]($style)'

[os.symbols]
Alpine = ''
Amazon = ''
Android = ''
Arch = '󰣇'
Artix = "󰣇"
CentOS = ''
Debian = ''
EndeavourOS = ''
Fedora = ''
FreeBSD = ''
Garuda = ''
Gentoo = ''
Linux = "󰌽"
Macos = ''
Manjaro = ''
Mint = ''
NetBSD = ''
NixOS = ''
OpenBSD = ''
openSUSE = ''
Pop = ''
Raspbian = ''
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
SUSE = ''
Ubuntu = "󰕈"
Unknown = ''
Windows = ''

[git_branch]
symbol = ""
style = "bg:bg-medium"
format = '[[$symbol $branch ](fg:blue bg:bg-medium)]($style)'

[git_status]
disabled = true
style = "bg:bg-medium"
format = '[[$all_status$ahead_behind](bg:bg-medium)]($style)'
conflicted = "[~$count ](fg:green bg:bg-medium)"
ahead = "[⇡$count ](fg:green bg:bg-medium)"
behind = "[⇣$count ](fg:green bg:bg-medium)"
diverged = "[⇡$ahead_count ⇣$behind_count ](fg:green bg:bg-medium)"
up_to_date = ""
untracked = "[?$count ](fg:yellow bg:bg-medium)"
stashed = "[*$count ](fg:green bg:bg-medium)"
modified = "[!$count ](fg:yellow bg:bg-medium)"
staged = "[+$count ](fg:yellow bg:bg-medium)"
renamed = "[»$count ](fg:yellow bg:bg-medium)"
deleted = "[✘$count ](fg:red-bright bg:bg-medium)"

[nix_shell]
style = "bg:bg-dark"
format = '[[ $state ](fg:blue bg:bg-dark)]($style)'
impure_msg = "impure "
pure_msg = "pure "
unknown_msg = ""

[nodejs]
symbol = ""
style = "bg:bg-dark"
format = '[[ $symbol ($version) ](fg:blue bg:bg-dark)]($style)'

[rust]
symbol = ""
style = "bg:bg-dark"
format = '[[ $symbol ($version) ](fg:blue bg:bg-dark)]($style)'

[python]
symbol = ""
style = "bg:bg-dark"
format = '[[ $symbol ($version) ](fg:blue bg:bg-dark)]($style)'

[time]
disabled = false
time_format = "%R"                                      # Hour:Minute Format
style = "bg:bg-darker"
format = '[[ $time ](fg:fg-light bg:bg-darker)]($style)'
