format = """
[░▒▓](#7aa2f7)\
[ 󰌽 ](bg:#7aa2f7 fg:#1a1b26)\
[](bg:#7aa2f7 fg:#7aa2f7)\
$directory\
[](fg:#7aa2f7 bg:#292e42)\
$git_branch\
$git_status\
[](fg:#292e42 bg:#1a1b26)\
$nix_shell\
[](fg:#1a1b26 bg:#16161e)\
$time\
[ ](fg:#16161e)\
\n$character"""

[directory]
style = "fg:#1a1b26 bg:#7aa2f7 bold"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
fish_style_pwd_dir_length = 1
truncate_to_repo = false

[git_branch]
symbol = ""
style = "bg:#292e42"
format = '[[ $symbol $branch ](fg:#7aa2f7 bg:#292e42)]($style)'

[git_status]
style = "bg:#292e42"
format = '[[$all_status$ahead_behind](bg:#292e42)]($style)'
conflicted = "[~$count ](fg:#5fd700 bg:#292e42)"
ahead = "[⇡$count ](fg:#5fd700 bg:#292e42)"
behind = "[⇣$count ](fg:#5fd700 bg:#292e42)"
diverged = "[⇡$ahead_count ⇣$behind_count ](fg:#5fd700 bg:#292e42)"
up_to_date = ""
untracked = "[?$count ](fg:#d7af00 bg:#292e42)"
stashed = "[*$count ](fg:#5fd700 bg:#292e42)"
modified = "[!$count ](fg:#d7af00 bg:#292e42)"
staged = "[+$count ](fg:#d7af00 bg:#292e42)"
renamed = "[»$count ](fg:#d7af00 bg:#292e42)"
deleted = "[✘$count ](fg:#d70000 bg:#292e42)"

[nix_shell]
style = "bg:#1a1b26"
format = '[[ $state ](fg:#7aa2f7 bg:#1a1b26)]($style)'
impure_msg = "impure "
pure_msg = "pure "
unknown_msg = ""

[time]
disabled = false
time_format = "%R"                                      # Hour:Minute Format
style = "bg:#16161e"
format = '[[  $time ](fg:#a9b1d6 bg:#16161e)]($style)'
