name: Nix Flake Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    runs-on: linux
    container:
      image: nixos/nix:latest
      options: --user root
      env:
        NIX_CONFIG: "experimental-features = nix-command flakes"
    steps:
      - name: Checkout
        run: |
          set -eux
          git clone --recursive "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git" "$GITHUB_WORKSPACE"
          cd "$GITHUB_WORKSPACE"
          git checkout "${GITHUB_SHA}"

      - name: Flake check
        run: nix flake check

      - name: Format check
        run: nix fmt -- --check .
