yuki.packages {
  scoop = {
    "7zip",
    "bat",
    "biome",
    "codex",
    "duf",
    "eza",
    "fastfetch",
    "fd",
    "git",
    "gpg",
    "hyperfine",
    "innounp",
    "just",
    "lua",
    "luarocks",
    "mise",
    "neovim",
    "nodejs-lts",
    "oh-my-posh",
    "ollama",
    "openssh",
    "pipx",
    "pnpm",
    "ripgrep",
    "rustup",
    "sed",
    "syncthing",
    "typst",
    "yt-dlp",
    "zig",
    "zoxide",
    { name = "antigravity", bucket = "extras" },
    { name = "autohotkey", bucket = "extras" },
    { name = "calibre", bucket = "extras" },
    { name = "cc-switch", bucket = "extras" },
    { name = "cpu-z", bucket = "extras" },
    { name = "discord", bucket = "extras" },
    { name = "etcher", bucket = "extras" },
    { name = "figma", bucket = "extras" },
    { name = "flow-launcher", bucket = "extras" },
    { name = "foobar2000", bucket = "extras" },
    { name = "gitextensions", bucket = "extras" },
    { name = "github", bucket = "extras" },
    { name = "gpg4win", bucket = "extras" },
    { name = "handbrake", bucket = "extras" },
    { name = "hexchat", bucket = "extras" },
    { name = "hwinfo", bucket = "extras" },
    { name = "kitty", bucket = "extras" },
    { name = "libreoffice", bucket = "extras" },
    { name = "love", bucket = "extras" },
    { name = "msedgeredirect", bucket = "extras" },
    { name = "notepadplusplus", bucket = "extras" },
    { name = "obs-studio", bucket = "extras" },
    { name = "obsidian", bucket = "extras" },
    { name = "ollama-full", bucket = "extras" },
    { name = "qbittorrent", bucket = "extras" },
    { name = "rufus", bucket = "extras" },
    { name = "sharex", bucket = "extras" },
    { name = "slack", bucket = "extras" },
    { name = "spotify", bucket = "extras" },
    { name = "stretchly", bucket = "extras" },
    { name = "subtitleedit", bucket = "extras" },
    { name = "sumatrapdf", bucket = "extras" },
    { name = "terminal-icons", bucket = "extras" },
    { name = "tightvnc", bucket = "extras" },
    { name = "ungoogled-chromium", bucket = "extras" },
    { name = "vial", bucket = "extras" },
    { name = "vlc", bucket = "extras" },
    { name = "vscode", bucket = "extras" },
    { name = "windirstat", bucket = "extras" },
    { name = "zoom", bucket = "extras" },
    { name = "zotero", bucket = "extras" },
    { name = "FiraCode-NF", bucket = "nerd-fonts" },
    { name = "FiraCode-NF-Mono", bucket = "nerd-fonts" },
    { name = "FiraCode-NF-Propo", bucket = "nerd-fonts" },
    { name = "FiraMono-NF", bucket = "nerd-fonts" },
    { name = "FiraMono-NF-Mono", bucket = "nerd-fonts" },
    { name = "FiraMono-NF-Propo", bucket = "nerd-fonts" },
    { name = "lua51", bucket = "versions" },
    { name = "ollama-rocm", bucket = "versions" },
    { name = "wezterm-nightly", bucket = "versions" },
  },
}
